# Generated by Django 3.1.1 on 2021-06-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeapp', '0010_user_reg_u_email'),
        ('admin_sellerapp', '0003_auto_20210506_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_category', models.CharField(max_length=100)),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_details', models.CharField(max_length=200)),
                ('pro_price', models.IntegerField(max_length=5)),
                ('pro_rating', models.IntegerField(blank=True, max_length=1, null=True)),
                ('pro_quantity', models.IntegerField(max_length=3)),
                ('seller_email', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_image', models.ImageField(upload_to='Productimages')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_sellerapp.add_category')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.seller_reg')),
            ],
        ),
    ]
