# Generated by Django 3.1.1 on 2021-01-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='u_phone',
            field=models.CharField(max_length=11),
        ),
    ]
