# Generated by Django 3.1.1 on 2021-01-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20210110_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='u_pincode',
            field=models.CharField(max_length=6),
        ),
    ]
