# Generated by Django 3.1.1 on 2021-04-01 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0005_user_reg_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_reg',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_fullname', models.CharField(max_length=200)),
                ('s_shopname', models.CharField(max_length=200)),
                ('s_address', models.CharField(max_length=200)),
                ('s_location', models.CharField(max_length=200)),
                ('s_coverphoto', models.ImageField(upload_to='coverphoto')),
                ('s_profilepic', models.ImageField(upload_to='profilepic')),
                ('s_phone', models.IntegerField(max_length=10)),
                ('s_aadhaar', models.IntegerField(max_length=15)),
                ('s_idproof', models.ImageField(upload_to='idproof')),
                ('s_gstno', models.CharField(max_length=15)),
                ('s_pincode', models.IntegerField(max_length=6)),
                ('s_state', models.CharField(max_length=100)),
                ('s_district', models.CharField(max_length=100)),
                ('s_taluk', models.CharField(max_length=100)),
                ('s_email', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
