# Generated by Django 3.1.1 on 2021-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_auto_20210410_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_reg',
            name='s_aadhaar',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='seller_reg',
            name='s_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seller_reg',
            name='s_pincode',
            field=models.CharField(max_length=6),
        ),
    ]
