# Generated by Django 3.1.1 on 2021-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_auto_20210413_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_reg',
            name='sellerstate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
