# Generated by Django 3.1.1 on 2021-06-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_seller_reg_sellerstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='u_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
