# Generated by Django 3.1.1 on 2021-04-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='password',
        ),
    ]
