# Generated by Django 3.1.1 on 2021-05-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sellerapp', '0002_remove_approval_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addcategory',
            new_name='add_category',
        ),
    ]
